name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./greenswap-frontend

      - name: Build project
        run: sudo npm run build
        working-directory: ./greenswap-frontend

      - name: Copy build files to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}  
          key: ${{ secrets.EC2_PRIVATE_KEY }}  
          script: |
            cd /home/ec2-user/greenswap-frontend
            sudo rm -r /usr/share/nginx/html/dist
            sudo cp -r dist /usr/share/nginx/html/
            sudo systemctl restart nginx

      - name: Check nginx status
        run: ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo systemctl status nginx'
